### ISSUE TITLE
One more examle pls

### ISSUE THREAD

**Issue by popovn** [JakeCigar/jQuery.sortChildren#1]
**Can't understand how to sort this table:**
Can you add this to examples?

``` HTML
 <div class="Table">
    <div class="Title">
        <p>This is a Table</p>
    </div>
    <div class="Heading">
        <div class="Cell">
            <p>1</p>
        </div>
        <div class="Cell">
            <p>3</p>
        </div>
        <div class="Cell">
            <p>2</p>
        </div>
    </div>
    <div class="Row">
        <div class="Cell">
            <p>s</p>
        </div>
        <div class="Cell">
            <p>a</p>
        </div>
        <div class="Cell">
            <p>f</p>
        </div>
    </div>
    <div class="Row">
        <div class="Cell">
            <p>Row 2 Column 1</p>
        </div>
        <div class="Cell">
            <p>Row 2 Column 2</p>
        </div>
        <div class="Cell">
            <p>Row 2 Column 3</p>
        </div>
    </div>
</div>
```

**PS:**
 http://jakecigar.github.io/jQuery.sortChildren/
_Dosnt work... but if copy to jsfiddle.net everyfing is OK_

**Comment by JakeCigar** [comment]
Interesting! Which browser did you use? I added your "Table" to http://home.jejaju.com/github/jQuery.sortChildren/

**Comment by popovn** [comment]
Firefox 40.0.3 Ubuntu 15.04
http://home.jejaju.com/github/jQuery.sortChildren/
Now works thanks

**Comment by JakeCigar** [comment]
It works for me on Firefox 40.0.3 OS X. Did you check the dev tools or firebug to see if there are errors?

Is your "table" sorting the way you need it to?

**Comment by popovn** [comment]
"Table" works fine - tomorrow will try understand ))
Thank you

Dev tool didn’t try - tried  to find error in your code by jsfiddle.net... but everything was fine...

**Comment by popovn** [comment]
about my table..
Cant "catch" mistake ... see

i click on "3" =>nothing changes, then click on "3" another time
then click on "1" => nothing changes, then click on "1" another time...

**Comment by JakeCigar** [comment]
There is so little data, if it is already sorted in that order, nothing _seems_ to  happen. 

Add more data.

The demo code I wrote is just like table sorting demo above.

**Comment by popovn** [comment]
Sorry for disturb 
im not programmer and this "divs" make me so stupid
Can you look at real table, which i try to sort, if it it will not took a mach time from you?
I want to make userscript for cinemate.cc
Thanks for example but i cant to transform it for my needs.
I want to sort table on load by "Размер" - last row in that "div" (but 4d from right in table visual)
https://jsfiddle.net/3mx2hh65/

**Comment by JakeCigar** [comment]
This plugin sorts child nodes. Your nodes are not simple child nodes. I suggest you hire a programmer to write a custom sort for you.

**Comment by popovn** [comment]
ok thank you
